#!/usr/bin/sh

ln -s ~/.dotfiles/git/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/starship/.config/ ~/.config/
ln -s ~/.dotfiles/fish/.config/fish ~/.config/fish
ln -s ~/.dotfiles/nvim/.config/nvim ~/.config/nvim
