#!/bin/bash

ln -s ~/dotfiles/git/.gitconfig ~/
ln -s ~/dotfiles/starship/.config/starship.toml ~/.config/
ln -s ~/dotfiles/fish/.config/fish/ ~/.config/
ln -s ~/dotfiles/nvim/.config/nvim/ ~/.config/
ln -s ~/dotfiles/tmux/.tmux.conf ~/
ln -s ~/dotfiles/scripts/.local/scripts ~/.local/
